// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: core/proto/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientCommand_CommandType int32

const (
	ClientCommand_SUBSCRIBE   ClientCommand_CommandType = 0
	ClientCommand_PAUSE       ClientCommand_CommandType = 1
	ClientCommand_RESUME      ClientCommand_CommandType = 2
	ClientCommand_UNSUBSCRIBE ClientCommand_CommandType = 3
)

// Enum value maps for ClientCommand_CommandType.
var (
	ClientCommand_CommandType_name = map[int32]string{
		0: "SUBSCRIBE",
		1: "PAUSE",
		2: "RESUME",
		3: "UNSUBSCRIBE",
	}
	ClientCommand_CommandType_value = map[string]int32{
		"SUBSCRIBE":   0,
		"PAUSE":       1,
		"RESUME":      2,
		"UNSUBSCRIBE": 3,
	}
)

func (x ClientCommand_CommandType) Enum() *ClientCommand_CommandType {
	p := new(ClientCommand_CommandType)
	*p = x
	return p
}

func (x ClientCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_proto_game_proto_enumTypes[0].Descriptor()
}

func (ClientCommand_CommandType) Type() protoreflect.EnumType {
	return &file_core_proto_game_proto_enumTypes[0]
}

func (x ClientCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientCommand_CommandType.Descriptor instead.
func (ClientCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_core_proto_game_proto_rawDescGZIP(), []int{8, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_core_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_core_proto_game_proto_rawDescGZIP(), []int{0}
}

type PlanetList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Planets       []*Planet              `protobuf:"bytes,1,rep,name=planets,proto3" json:"planets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanetList) Reset() {
	*x = PlanetList{}
	mi := &file_core_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanetList) ProtoMessage() {}

func (x *PlanetList) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanetList.ProtoReflect.Descriptor instead.
func (*PlanetList) Descriptor() ([]byte, []int) {
	return file_core_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlanetList) GetPlanets() []*Planet {
	if x != nil {
		return x.Planets
	}
	return nil
}

type NPCList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Npcs          []*NPC                 `protobuf:"bytes,1,rep,name=npcs,proto3" json:"npcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NPCList) Reset() {
	*x = NPCList{}
	mi := &file_core_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NPCList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NPCList) ProtoMessage() {}

func (x *NPCList) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NPCList.ProtoReflect.Descriptor instead.
func (*NPCList) Descriptor() ([]byte, []int) {
	return file_core_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *NPCList) GetNpcs() []*NPC {
	if x != nil {
		return x.Npcs
	}
	return nil
}

type Planet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Resources     map[string]int32       `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Modifiers     map[string]float32     `protobuf:"bytes,4,rep,name=modifiers,proto3" json:"modifiers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	Buildings     []*Building            `protobuf:"bytes,5,rep,name=buildings,proto3" json:"buildings,omitempty"`
	Owner         *NPC                   `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Planet) Reset() {
	*x = Planet{}
	mi := &file_core_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Planet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Planet) ProtoMessage() {}

func (x *Planet) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Planet.ProtoReflect.Descriptor instead.
func (*Planet) Descriptor() ([]byte, []int) {
	return file_core_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *Planet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Planet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Planet) GetResources() map[string]int32 {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Planet) GetModifiers() map[string]float32 {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

func (x *Planet) GetBuildings() []*Building {
	if x != nil {
		return x.Buildings
	}
	return nil
}

func (x *Planet) GetOwner() *NPC {
	if x != nil {
		return x.Owner
	}
	return nil
}

type Building struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Production    map[string]int32       `protobuf:"bytes,3,rep,name=production,proto3" json:"production,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Modifiers     map[string]float32     `protobuf:"bytes,4,rep,name=modifiers,proto3" json:"modifiers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	BuildCost     map[string]int32       `protobuf:"bytes,5,rep,name=buildCost,proto3" json:"buildCost,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Building) Reset() {
	*x = Building{}
	mi := &file_core_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Building) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Building) ProtoMessage() {}

func (x *Building) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Building.ProtoReflect.Descriptor instead.
func (*Building) Descriptor() ([]byte, []int) {
	return file_core_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *Building) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Building) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Building) GetProduction() map[string]int32 {
	if x != nil {
		return x.Production
	}
	return nil
}

func (x *Building) GetModifiers() map[string]float32 {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

func (x *Building) GetBuildCost() map[string]int32 {
	if x != nil {
		return x.BuildCost
	}
	return nil
}

type NPC struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Offer                map[string]int32       `protobuf:"bytes,2,rep,name=offer,proto3" json:"offer,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Credits              int32                  `protobuf:"varint,3,opt,name=credits,proto3" json:"credits,omitempty"`
	Cargo                map[string]int32       `protobuf:"bytes,4,rep,name=cargo,proto3" json:"cargo,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MaxCargo             int32                  `protobuf:"varint,5,opt,name=maxCargo,proto3" json:"maxCargo,omitempty"`
	ColonizationCooldown string                 `protobuf:"bytes,6,opt,name=colonizationCooldown,proto3" json:"colonizationCooldown,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NPC) Reset() {
	*x = NPC{}
	mi := &file_core_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NPC) ProtoMessage() {}

func (x *NPC) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NPC.ProtoReflect.Descriptor instead.
func (*NPC) Descriptor() ([]byte, []int) {
	return file_core_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *NPC) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NPC) GetOffer() map[string]int32 {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *NPC) GetCredits() int32 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *NPC) GetCargo() map[string]int32 {
	if x != nil {
		return x.Cargo
	}
	return nil
}

func (x *NPC) GetMaxCargo() int32 {
	if x != nil {
		return x.MaxCargo
	}
	return 0
}

func (x *NPC) GetColonizationCooldown() string {
	if x != nil {
		return x.ColonizationCooldown
	}
	return ""
}

type UniverseState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Planets       *PlanetList            `protobuf:"bytes,1,opt,name=planets,proto3" json:"planets,omitempty"`
	Npcs          *NPCList               `protobuf:"bytes,2,opt,name=npcs,proto3" json:"npcs,omitempty"`
	Events        []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniverseState) Reset() {
	*x = UniverseState{}
	mi := &file_core_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniverseState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniverseState) ProtoMessage() {}

func (x *UniverseState) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniverseState.ProtoReflect.Descriptor instead.
func (*UniverseState) Descriptor() ([]byte, []int) {
	return file_core_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *UniverseState) GetPlanets() *PlanetList {
	if x != nil {
		return x.Planets
	}
	return nil
}

func (x *UniverseState) GetNpcs() *NPCList {
	if x != nil {
		return x.Npcs
	}
	return nil
}

func (x *UniverseState) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Target         int32                  `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	TargetPlanet   string                 `protobuf:"bytes,3,opt,name=targetPlanet,proto3" json:"targetPlanet,omitempty"`
	TargetBuilding string                 `protobuf:"bytes,4,opt,name=targetBuilding,proto3" json:"targetBuilding,omitempty"`
	ResourceBoost  map[string]float32     `protobuf:"bytes,5,rep,name=resourceBoost,proto3" json:"resourceBoost,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	Duration       int32                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	RemainingTicks int32                  `protobuf:"varint,7,opt,name=remainingTicks,proto3" json:"remainingTicks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_core_proto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_core_proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Event) GetTargetPlanet() string {
	if x != nil {
		return x.TargetPlanet
	}
	return ""
}

func (x *Event) GetTargetBuilding() string {
	if x != nil {
		return x.TargetBuilding
	}
	return ""
}

func (x *Event) GetResourceBoost() map[string]float32 {
	if x != nil {
		return x.ResourceBoost
	}
	return nil
}

func (x *Event) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Event) GetRemainingTicks() int32 {
	if x != nil {
		return x.RemainingTicks
	}
	return 0
}

type ClientCommand struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          ClientCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.ClientCommand_CommandType" json:"type,omitempty"`
	Payload       string                    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCommand) Reset() {
	*x = ClientCommand{}
	mi := &file_core_proto_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCommand) ProtoMessage() {}

func (x *ClientCommand) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCommand.ProtoReflect.Descriptor instead.
func (*ClientCommand) Descriptor() ([]byte, []int) {
	return file_core_proto_game_proto_rawDescGZIP(), []int{8}
}

func (x *ClientCommand) GetType() ClientCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return ClientCommand_SUBSCRIBE
}

func (x *ClientCommand) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_core_proto_game_proto protoreflect.FileDescriptor

const file_core_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x15core/proto/game.proto\x12\x05proto\"\a\n" +
	"\x05Empty\"5\n" +
	"\n" +
	"PlanetList\x12'\n" +
	"\aplanets\x18\x01 \x03(\v2\r.proto.PlanetR\aplanets\")\n" +
	"\aNPCList\x12\x1e\n" +
	"\x04npcs\x18\x01 \x03(\v2\n" +
	".proto.NPCR\x04npcs\"\xf5\x02\n" +
	"\x06Planet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12:\n" +
	"\tresources\x18\x03 \x03(\v2\x1c.proto.Planet.ResourcesEntryR\tresources\x12:\n" +
	"\tmodifiers\x18\x04 \x03(\v2\x1c.proto.Planet.ModifiersEntryR\tmodifiers\x12-\n" +
	"\tbuildings\x18\x05 \x03(\v2\x0f.proto.BuildingR\tbuildings\x12 \n" +
	"\x05owner\x18\x06 \x01(\v2\n" +
	".proto.NPCR\x05owner\x1a<\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eModifiersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xac\x03\n" +
	"\bBuilding\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12?\n" +
	"\n" +
	"production\x18\x03 \x03(\v2\x1f.proto.Building.ProductionEntryR\n" +
	"production\x12<\n" +
	"\tmodifiers\x18\x04 \x03(\v2\x1e.proto.Building.ModifiersEntryR\tmodifiers\x12<\n" +
	"\tbuildCost\x18\x05 \x03(\v2\x1e.proto.Building.BuildCostEntryR\tbuildCost\x1a=\n" +
	"\x0fProductionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eModifiersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a<\n" +
	"\x0eBuildCostEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xd1\x02\n" +
	"\x03NPC\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x05offer\x18\x02 \x03(\v2\x15.proto.NPC.OfferEntryR\x05offer\x12\x18\n" +
	"\acredits\x18\x03 \x01(\x05R\acredits\x12+\n" +
	"\x05cargo\x18\x04 \x03(\v2\x15.proto.NPC.CargoEntryR\x05cargo\x12\x1a\n" +
	"\bmaxCargo\x18\x05 \x01(\x05R\bmaxCargo\x122\n" +
	"\x14colonizationCooldown\x18\x06 \x01(\tR\x14colonizationCooldown\x1a8\n" +
	"\n" +
	"OfferEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"CargoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x86\x01\n" +
	"\rUniverseState\x12+\n" +
	"\aplanets\x18\x01 \x01(\v2\x11.proto.PlanetListR\aplanets\x12\"\n" +
	"\x04npcs\x18\x02 \x01(\v2\x0e.proto.NPCListR\x04npcs\x12$\n" +
	"\x06events\x18\x03 \x03(\v2\f.proto.EventR\x06events\"\xcc\x02\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x05R\x06target\x12\"\n" +
	"\ftargetPlanet\x18\x03 \x01(\tR\ftargetPlanet\x12&\n" +
	"\x0etargetBuilding\x18\x04 \x01(\tR\x0etargetBuilding\x12E\n" +
	"\rresourceBoost\x18\x05 \x03(\v2\x1f.proto.Event.ResourceBoostEntryR\rresourceBoost\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\x12&\n" +
	"\x0eremainingTicks\x18\a \x01(\x05R\x0eremainingTicks\x1a@\n" +
	"\x12ResourceBoostEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xa5\x01\n" +
	"\rClientCommand\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .proto.ClientCommand.CommandTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"D\n" +
	"\vCommandType\x12\r\n" +
	"\tSUBSCRIBE\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\x12\n" +
	"\n" +
	"\x06RESUME\x10\x02\x12\x0f\n" +
	"\vUNSUBSCRIBE\x10\x032\xb0\x01\n" +
	"\x0fUniverseService\x12-\n" +
	"\n" +
	"GetPlanets\x12\f.proto.Empty\x1a\x11.proto.PlanetList\x12'\n" +
	"\aGetNPCs\x12\f.proto.Empty\x1a\x0e.proto.NPCList\x12E\n" +
	"\x13StreamUniverseState\x12\x14.proto.ClientCommand\x1a\x14.proto.UniverseState(\x010\x01B\x12Z\x10core/proto;protob\x06proto3"

var (
	file_core_proto_game_proto_rawDescOnce sync.Once
	file_core_proto_game_proto_rawDescData []byte
)

func file_core_proto_game_proto_rawDescGZIP() []byte {
	file_core_proto_game_proto_rawDescOnce.Do(func() {
		file_core_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_game_proto_rawDesc), len(file_core_proto_game_proto_rawDesc)))
	})
	return file_core_proto_game_proto_rawDescData
}

var file_core_proto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_core_proto_game_proto_goTypes = []any{
	(ClientCommand_CommandType)(0), // 0: proto.ClientCommand.CommandType
	(*Empty)(nil),                  // 1: proto.Empty
	(*PlanetList)(nil),             // 2: proto.PlanetList
	(*NPCList)(nil),                // 3: proto.NPCList
	(*Planet)(nil),                 // 4: proto.Planet
	(*Building)(nil),               // 5: proto.Building
	(*NPC)(nil),                    // 6: proto.NPC
	(*UniverseState)(nil),          // 7: proto.UniverseState
	(*Event)(nil),                  // 8: proto.Event
	(*ClientCommand)(nil),          // 9: proto.ClientCommand
	nil,                            // 10: proto.Planet.ResourcesEntry
	nil,                            // 11: proto.Planet.ModifiersEntry
	nil,                            // 12: proto.Building.ProductionEntry
	nil,                            // 13: proto.Building.ModifiersEntry
	nil,                            // 14: proto.Building.BuildCostEntry
	nil,                            // 15: proto.NPC.OfferEntry
	nil,                            // 16: proto.NPC.CargoEntry
	nil,                            // 17: proto.Event.ResourceBoostEntry
}
var file_core_proto_game_proto_depIdxs = []int32{
	4,  // 0: proto.PlanetList.planets:type_name -> proto.Planet
	6,  // 1: proto.NPCList.npcs:type_name -> proto.NPC
	10, // 2: proto.Planet.resources:type_name -> proto.Planet.ResourcesEntry
	11, // 3: proto.Planet.modifiers:type_name -> proto.Planet.ModifiersEntry
	5,  // 4: proto.Planet.buildings:type_name -> proto.Building
	6,  // 5: proto.Planet.owner:type_name -> proto.NPC
	12, // 6: proto.Building.production:type_name -> proto.Building.ProductionEntry
	13, // 7: proto.Building.modifiers:type_name -> proto.Building.ModifiersEntry
	14, // 8: proto.Building.buildCost:type_name -> proto.Building.BuildCostEntry
	15, // 9: proto.NPC.offer:type_name -> proto.NPC.OfferEntry
	16, // 10: proto.NPC.cargo:type_name -> proto.NPC.CargoEntry
	2,  // 11: proto.UniverseState.planets:type_name -> proto.PlanetList
	3,  // 12: proto.UniverseState.npcs:type_name -> proto.NPCList
	8,  // 13: proto.UniverseState.events:type_name -> proto.Event
	17, // 14: proto.Event.resourceBoost:type_name -> proto.Event.ResourceBoostEntry
	0,  // 15: proto.ClientCommand.type:type_name -> proto.ClientCommand.CommandType
	1,  // 16: proto.UniverseService.GetPlanets:input_type -> proto.Empty
	1,  // 17: proto.UniverseService.GetNPCs:input_type -> proto.Empty
	9,  // 18: proto.UniverseService.StreamUniverseState:input_type -> proto.ClientCommand
	2,  // 19: proto.UniverseService.GetPlanets:output_type -> proto.PlanetList
	3,  // 20: proto.UniverseService.GetNPCs:output_type -> proto.NPCList
	7,  // 21: proto.UniverseService.StreamUniverseState:output_type -> proto.UniverseState
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_core_proto_game_proto_init() }
func file_core_proto_game_proto_init() {
	if File_core_proto_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_game_proto_rawDesc), len(file_core_proto_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_game_proto_goTypes,
		DependencyIndexes: file_core_proto_game_proto_depIdxs,
		EnumInfos:         file_core_proto_game_proto_enumTypes,
		MessageInfos:      file_core_proto_game_proto_msgTypes,
	}.Build()
	File_core_proto_game_proto = out.File
	file_core_proto_game_proto_goTypes = nil
	file_core_proto_game_proto_depIdxs = nil
}
